# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
    
    - name: Build Java project
        run: |
          cd backend  # Change to your Java app directory
          ./mvnw clean package -DskipTests  # Assuming you're using Maven

      - name: Build Docker image for Java
        run: |
          cd backend  # Change to your Java app directory
          docker build -t 
praveendshankar0502/javareact-app:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Java Docker image
        run: |
          docker push praveendshankar0502/javareact-app:latest

      - name: Build React project
        run: |
          cd frontend  # Change to your React app directory
          npm install
          npm run build

      - name: Build Docker image for React
        run: |
          cd react-app  # Change to your React app directory
          docker build -t praveendshankar0502/react-app:latest .

      - name: Push React Docker image
        run: |
          docker push praveendshankar0502/react-app:latest
